"""История LEGO по-английски — частями по одному сообщению Telegram.

Зачем: владелец (15 сен 2026) попросил, чтобы бот геопозиции в ответ на
включённую трансляцию присылал не короткое «идёт», а очень длинный текст:
точка с картой уезжает далеко вверх, и листать до неё приходится долго.
Предел одного сообщения в Telegram — 4096 знаков, поэтому текст порезан на
части; бот шлёт их подряд. Текст свой, не перепечатка.
"""

PARTS = [
"""THE HISTORY OF LEGO — PART ONE: A CARPENTER IN BILLUND

The story begins in a small town in the middle of Jutland, the flat and windy peninsula that makes up most of Denmark. Billund in the early twentieth century was a village of a few hundred people, surrounded by heath and farmland, with no particular reason to be remembered by anyone. In 1916 a carpenter named Ole Kirk Kristiansen bought a woodworking shop there. He was born in 1891 as the tenth child of a poor farming family, had learned his trade as a journeyman, and wanted nothing more ambitious than to build houses and furniture for the farmers around him.

For a while that is exactly what he did. The workshop made doors, window frames, ladders and stools. It also burned down, in 1924, when two of his young sons set fire to a pile of wood shavings while playing. Ole Kirk rebuilt it larger than before, which turned out to be a habit: he rebuilt after a fire more than once in his life, and every time he built bigger than he strictly needed.

The Great Depression reached Denmark at the start of the 1930s. Farmers stopped ordering houses, and a carpenter with a large workshop and no customers had to think. Ole Kirk began to make small household items that people could still afford: stepladders, ironing boards, and, almost as an afterthought, wooden toys. The toys were a small part of the output, but they sold, and children did not care about the economy.

In 1932 the toy production began in earnest. The first products were simple: pull-along animals, cars, a yo-yo that briefly became a craze and then crashed as crazes do, leaving Ole Kirk with a warehouse of unsold yo-yo halves. He turned them into wheels for toy trucks. That refusal to waste anything, and the readiness to turn a failure into the next product, were part of the company's character before the company had a name.

The name came in 1934. Ole Kirk held a small competition among his employees, and the winning entry was his own. He took the Danish phrase "leg godt", which means "play well", and compressed it into LEGO. Only much later did someone point out that in Latin the word can be read as "I put together" or "I assemble". The company has always said this was a happy accident rather than a plan, and there is no reason to doubt it: a carpenter in Billund in 1934 was not naming toys in Latin.

By the end of the decade the workshop employed around a dozen people. The best-known object from those years is a wooden duck on wheels, painted with a patient hand, whose beak opened and closed as it rolled. There is a story about the duck that the company has told for generations. Godtfred, Ole Kirk's son, came to his father pleased with himself: he had saved money by giving a batch of ducks two coats of varnish instead of the usual three. His father sent him back to the workshop to unpack every box and apply the third coat. The motto that came out of that evening, "only the best is good enough", was carved into a wooden sign and hung in the workshop, and it has hung in one form or another over the company ever since.

The war years were hard but not fatal. Denmark was occupied, materials were scarce, and imports of toys stopped, which oddly helped a small Danish toymaker: there was less competition. The factory burned again in 1942, and again Ole Kirk rebuilt it. By 1946 the company was ready for the decision that changed everything, and it had almost nothing to do with wood.""",

"""THE HISTORY OF LEGO — PART TWO: THE PLASTIC MACHINE

In 1946 Ole Kirk Kristiansen saw a demonstration of a plastic injection moulding machine, a British-made device that could turn granules of cellulose acetate into small, precise shapes. It cost roughly thirty thousand Danish kroner, about twice the company's profit for the previous year. His sons thought the purchase was reckless. He bought it anyway, and in 1947 it became the first machine of its kind in Denmark.

The first plastic products were not bricks. There was a rattle in the shape of a fish, a small tractor that came as a kit, and a teddy bear. Plastic was still regarded with suspicion by many parents, who considered it cheap and cold compared with wood, and retailers were not enthusiastic either. The company kept its wooden line going for years, and for a long time plastic was the smaller business.

Along with the machine came samples of what could be made with it. One of them was a British toy: the Kiddicraft Self-Locking Building Brick, designed and patented in the 1940s by Hilary Fisher Page, a child psychologist turned toymaker who believed that children learned best through free play with simple, well-made pieces. His brick was hollow, with studs on top and slots in the sides, and it could be stacked but did not grip very well.

In 1949 LEGO began producing its own version, called Automatic Binding Bricks. The early ones were close relatives of the Kiddicraft brick: the same proportions, the same slots in the side walls, studs on top and a hollow underside. They were sold in Denmark in small boxes, and they were not a sensation. Many toy dealers sent them back. The company itself was not yet convinced that a brick, rather than a toy shaped like something, was what children wanted.

The name changed in 1953 to LEGO Mursten, simply "LEGO bricks", and the letters were moulded into the top of every stud, a small detail that has remained to this day. The colours were limited: red, white, yellow, blue and a little green, chosen by instinct rather than research. The plastic was cellulose acetate, which was easy to mould but had a tendency to warp slightly over the years, so a brick from 1953 may no longer be perfectly square today.

The decisive idea arrived in 1954 not in Billund but on a ferry. Godtfred Kirk Christiansen, by then the junior managing director, was travelling to a toy fair in England and fell into conversation with the head buyer of a large department store. The buyer complained that the toy industry had no system: every product stood alone, was played with for a while and forgotten. Godtfred came home and wrote down a list of principles for what a toy system should be. It should be small enough to be played with indoors, offer unlimited play possibilities, suit boys and girls of every age, be a classic rather than a fashion, be easy to expand, and be available everywhere with every part fitting every other part.

In 1955 the company launched the LEGO System i Leg, the System of Play, built around a Town Plan: a printed board with roads, and sets of bricks, small cars and trees to fill the empty spaces. The point was that the sets belonged together. A child who received a set for a birthday could add another at Christmas and everything would fit. This was the idea that turned a brick into a product line, and it was exported the following year when a sales office opened in Germany, LEGO's first foreign market and for decades its largest.""",

"""THE HISTORY OF LEGO — PART THREE: THE BRICK THAT HOLDS

The early bricks had a problem that every child noticed: models fell apart. The hollow brick gripped its neighbours only along the outer walls, and a wall of them could be lifted, but a car could not be swung around the room. Godtfred Kirk Christiansen spent years looking for a better coupling, and the company experimented with various shapes inside the brick.

The answer was patented on 28 January 1958. Inside the hollow underside of the brick, tubes were added: one tube in the middle of a two-by-two brick, three in a row in a two-by-four. When a brick was pressed onto another, the studs of the lower brick were gripped not just by the walls but by the tubes, on three sides at once. The connection was firm, it could be released by a child without tools, and it could be repeated thousands of times before the plastic wore. The patent application listed several alternative designs, in case the tubes did not work, but the tubes worked, and every brick made since then uses them. A brick moulded in 1958 still clicks onto a brick moulded this morning.

The same year Ole Kirk Kristiansen died, and Godtfred took over a company of around one hundred and forty employees. Two years later, in 1960, another fire destroyed the warehouse of wooden toys. Godtfred did not rebuild that part of the business. From 1960 LEGO made plastic toys only, and within a few years it made almost nothing but the System. His brothers, who had wanted to keep the wooden toys, left the company.

Growth in the 1960s was fast and outward. Sales offices opened across Western Europe. In North America the company did not sell directly at first but licensed the product to Samsonite, the luggage manufacturer, which made and sold LEGO in the United States and Canada from 1961. The arrangement was never a happy one. Samsonite treated the bricks as one product among many, quality varied, and the company bought back the rights in the early 1970s and set up its own American operation in Connecticut.

The product itself kept changing in ways that seem obvious now. Wheels arrived in 1962, and with them the first real vehicles. Sloped roof bricks came in 1958, allowing houses with proper roofs. In 1963 the plastic was changed from cellulose acetate to ABS, acrylonitrile butadiene styrene, a harder and more stable material that keeps its colour and shape. Building instructions in printed booklets appeared in sets from 1964; before that, the picture on the box was the instruction. A train system with a small battery motor arrived in 1966.

The company was moving from a toy maker to something closer to a brand, and in 1968 it built the physical proof: Legoland in Billund, a park of models built from millions of bricks, with a miniature Denmark, a miniature Amsterdam and a miniature Rhine valley. The founders expected perhaps a few hundred thousand visitors a year. The park received six hundred thousand in its first season, and Billund, still a village with one main road, suddenly had an airport, a hotel and traffic. The airport had been built by the company in 1964 so that its own aircraft and its customers could reach the place at all.

In 1969 a second brick was born, twice the size of the first in every dimension. It was called Duplo, from the Latin for double, and it was meant for children too young for the small pieces. The clever part was that a Duplo brick fits on top of an ordinary brick and vice versa, so a family with children of different ages could build together and nothing had to be thrown away when a child grew up.""",

"""THE HISTORY OF LEGO — PART FOUR: THE MINIFIGURE AND THE THEMES

The 1970s gave LEGO the things that people today think of first when they hear the name. Until then the sets were buildings and vehicles without inhabitants: a house with no one in it, a car with no driver. In 1974 the first figures arrived, large by later standards, with round heads and arms that moved, sold as a LEGO family with a mother, a father, children and a grandmother. They could sit in a chair but not in a car, and they had no hands.

The real answer came in 1978, after years of prototypes by a designer named Jens Nygaard Knudsen. The minifigure was four bricks tall, its legs moved, its arms moved, its hands could hold a cup, a wrench, a sword or a steering wheel, and its head was a simple yellow cylinder with two dots for eyes and a smile. The face was made deliberately neutral so that any child could imagine any person into it. Yellow was chosen precisely because it was nobody's skin colour. The figure was patented, and it turned every set into a story: the house now had a family, the police car had a policeman, the castle had knights.

The same year the company introduced what it called themes, and three of them defined childhoods for a decade. Town was the everyday world of petrol stations, fire engines and ambulances. Castle began with a single yellow castle and grew into rival factions with their own shields and colours. Space, launched in 1978 as well, offered grey and blue spacecraft, moon bases and astronauts in coloured suits, on a bumpy grey baseplate that pretended to be the surface of another planet. A child could stay in Town, escape to Space, and still use the same bricks for both.

A year earlier, in 1977, a different line had appeared for older builders. It was first called Expert Builder and later became Technic: beams with holes, axles, gears, and eventually pneumatic cylinders and motors, so that a model could have working steering, a gearbox, or a crane that lifted. Technic taught engineering without lectures, and a generation of engineers has admitted in interviews that this was where they started.

The logo took its familiar form in 1973: white letters with a black outline and a yellow inner line on a red square, so that it could be recognised on a shelf from across a shop. Slight adjustments came later, but a box from 1973 looks like a box from today.

In 1979 the third generation took over. Kjeld Kirk Kristiansen, Godtfred's son, became president and chief executive. He had grown up as the child on the cover of many LEGO boxes, spelled his surname with the older Danish spelling, and had a clear view that the company should be organised around ages and stages: Duplo for the youngest, the System for children, Technic for teenagers. The 1980s were built on that plan.

The decade also brought the first serious use of the brick in education. Teachers had used LEGO in classrooms since the 1960s, but in 1980 the company created a dedicated educational products department, later called Dacta, which sold sets with worksheets to schools and began a long relationship with the Massachusetts Institute of Technology. That relationship would produce, twenty years later, something that neither side could have described in 1980: a brick with a computer inside it.""",

"""THE HISTORY OF LEGO — PART FIVE: GROWING UP IN THE EIGHTIES

The 1980s were comfortable years. Sales grew almost every year, factories opened in Switzerland and the United States to add to the ones in Denmark and Germany, and the company reached its fiftieth birthday in 1982 as one of the largest toy makers in the world without ever having sold a share to the public. It remained, and remains, privately owned by the family.

The product lines deepened rather than widened. Town gained an airport, a harbour, and a police station that seemed to be rebuilt every three years. Castle split into factions: the Crusaders, the Black Falcons, the Forestmen who lived in trees and robbed the others. Space became Futuron and Blacktron, with white-and-blue heroes and black-and-yellow villains, and later the Space Police to arrest them. In 1989 Pirates arrived and broke a rule: for the first time the minifigures had faces that were not the standard smile. Pirates had beards, eye patches and scowls, and the ships had sails and cannons that actually fired small plastic balls.

Technic added pneumatics in 1984, so that a model could lift with compressed air, and Light and Sound sets in 1986 put small bulbs and a siren into a police car. The Model Team line of 1990 aimed at teenagers who wanted a truck that looked like a truck, without a story attached.

In 1985 the company founded a professorship at MIT, the LEGO Papert Professorship of Learning Research, named after Seymour Papert, the mathematician who had argued that children learn by building things that matter to them. His 1980 book on the subject was called Mindstorms, and the name would later be borrowed.

The first LEGO fan competitions, the first specialist magazines and the first adult collectors also appeared in this decade, though the company did not know quite what to do with adults who built. Its marketing was addressed to parents buying for children. Adults who bought sets for themselves were regarded as an amusing anomaly.

By 1990 LEGO was among the ten largest toy companies in the world. It made more than a billion elements a year in a system of moulds so precise that the tolerance on a stud was measured in thousandths of a millimetre. A brick that could not fit onto every other brick was not a brick, and the factories threw away the ones that failed. The proportion rejected was very small, and the company was proud of it, but the same perfectionism made it slow. Decisions took years, and a product that did not fit the philosophy could be discussed to death.

Towards the end of the decade something began to change in the world outside Billund. Video games, first in arcades and then in living rooms, competed for the same hours of the afternoon that had once gone to bricks. The patents on the basic brick had begun to expire in the late 1970s, and in the 1980s and 1990s competitors appeared with compatible bricks at lower prices. LEGO responded with lawsuits in many countries, winning some and losing others; the general result, settled over decades, was that the shape of the brick could not be protected forever as a trademark, and that competitors could make studs and tubes as long as they did not use the name. The company would have to compete on quality and imagination rather than on the law.""",

"""THE HISTORY OF LEGO — PART SIX: THE NINETIES AND THE FIRST WARNINGS

The 1990s began well and ended badly. In 1992 the company set two Guinness records with the largest LEGO castle and the longest LEGO structure. In 1993 the Belville line was introduced for girls, with larger figures and pastel colours, and it sold reasonably without ever becoming loved. In 1995 Godtfred Kirk Christiansen died at the age of seventy-five, the man who had turned a brick into a system.

In 1996 a second Legoland opened, in Windsor near London, on the site of a former safari park, and it was a success. The company took this as a sign that parks were a business to expand, and it would come to regret the enthusiasm. In 1997 LEGO Island appeared, the company's first video game developed in-house, followed by many licensed games of mixed quality.

The most interesting product of the decade came from the long relationship with MIT. In 1998 the company released LEGO Mindstorms, a programmable brick with a small computer inside, sensors for touch and light, and motors that plugged into Technic. A child, or an adult, could build a robot and write a program for it on a home computer. The kit sold far beyond expectations, and within weeks of the launch, adult enthusiasts had reverse-engineered the firmware and published their own programming tools. The company's lawyers wanted to stop them. Its leaders decided instead to leave the hackers alone and, in later versions, to write the right to tinker into the licence. It was one of the first times a large toy company treated its adult fans as partners rather than pirates.

Also in 1998, for the first time in its history, the LEGO Group posted a loss. The deficit was around two hundred million Danish kroner, and one thousand employees were laid off. The company brought in a chief operating officer from the outside, Poul Plougmann, with a mandate to make LEGO a lifestyle brand rather than a brick maker.

The strategy that followed was ambitious and unfocused. There were LEGO clothes, LEGO watches, a LEGO television studio, LEGO software, and new themes that moved further and further from the brick. In 1999 the company took a step it had resisted for decades and signed its first licence for a film property: LEGO Star Wars. The sets sold enormously, and the Star Wars line has been in continuous production ever since, but it also taught a dangerous lesson: that a licence could produce a hit without the years of internal design that an original theme required.

The same year Legoland California opened near San Diego, the third park, and the brick was named Toy of the Century by Fortune magazine and by the British Association of Toy Retailers. From the outside the company looked like a triumph. From the inside the accounts were beginning to say something else.""",

"""THE HISTORY OF LEGO — PART SEVEN: THE CRISIS

Between 2000 and 2003 the LEGO Group came close to disappearing. The causes were many and, in retrospect, easy to list. The company had expanded into too many businesses at once. The theme parks in Billund, Windsor, California and, from 2002, Günzburg in Germany consumed capital and management attention. The number of different elements in production had exploded: from around six thousand in 1997 to more than fourteen thousand by 2004, many of them used in only one set. Every new element required a new steel mould costing tens of thousands of euros, and the warehouses filled with pieces that nobody could reuse.

New themes were designed by people with little connection to the brick. Galidor, launched in 2002 alongside a television series, consisted of action figures with almost no building at all; it failed completely. Jack Stone sets used large pre-moulded pieces so that a child could finish a model in minutes, which took away the reason for building. The Explore line replaced the Duplo name for a while, confusing parents who had bought Duplo for thirty years.

There was one genuine success, and it kept the lights on: Bionicle, launched in 2001, a line of buildable action figures with an invented mythology of islands, masks and elemental heroes, told through comics, online games and films. Bionicle was designed in-house, it used Technic parts in new ways, and it sold in enormous numbers to boys who had stopped buying City sets. For several years it was said to account for a large share of the company's profit.

In 2003 the LEGO Group lost roughly 1.4 billion Danish kroner, and in 2004 it lost again. Sales fell by a quarter in a single year. Kjeld Kirk Kristiansen put around eight hundred million kroner of his own money into the company to keep it solvent. The banks were watching. Analysts wondered aloud whether Mattel would buy it.

In October 2004 Kjeld stepped aside as chief executive, and for the first time the company was run by someone who was not a member of the family. Jørgen Vig Knudstorp was thirty-six years old, a former McKinsey consultant who had joined the company in 2001 as director of strategic development and who had spent two years writing reports explaining, in numbers, that the company was heading for a wall. He was given the job of turning it around, and he did it by reversing almost everything that the previous decade had done.

The parks were sold in 2005 to the Merlin Entertainments group, with the LEGO Group keeping a minority stake, so that the brand stayed on the gates but the cost left the books. The video game studio was closed. The clothing and watch businesses were licensed out. Factories in Switzerland and the United States were closed and production moved partly to Mexico and later to Hungary and the Czech Republic, painfully for a company that had never before laid off Danish workers in large numbers. The number of elements was cut in half, and every new piece had to be justified by designers to a committee that asked whether an existing piece could do the job.

Most importantly, the company went back to the brick. The mantra of the turnaround was that LEGO should make products that its core customers, children between five and nine and their parents, could recognise as LEGO. Themes were tested with children before launch. Adult fans were invited to Billund to say what they thought. By 2006 the company was profitable again, and by 2008 it was growing faster than the toy industry as a whole.""",

"""THE HISTORY OF LEGO — PART EIGHT: THE RENAISSANCE

The recovery after 2005 became one of the most studied corporate turnarounds of its era, and it produced a run of products that defined the company's second golden age. The discipline that had been imposed in the crisis, fewer elements and stricter testing, turned out to make better sets rather than duller ones.

City replaced Town and became the backbone of the range again, with fire stations, police stations and construction sites that sold year after year. Star Wars continued. In 2007 the first modular building appeared, Cafe Corner, a detailed street corner for adult builders that connected to further buildings along a standard edge; a new one has been released every year since, and the line is collected like stamps. LEGO Architecture arrived in 2008, small monochrome models of famous buildings sold in museum shops and airports to adults who would never have entered a toy department.

In 2008 the company also began an experiment with a Japanese website called Cuusoo, where anyone could propose a set and, if it collected enough votes, the company would consider producing it. The idea became LEGO Ideas in 2014, and it has produced sets designed by fans from all over the world: a Saturn V rocket, a typewriter, a ship in a bottle, the women of NASA, a working piano.

Ninjago, launched in 2011, proved that an original theme could still succeed against licensed properties. It combined ninjas, dragons, spinning tops and a long-running animated series, and it has been produced continuously for more than a decade, which is longer than almost any theme except City and Star Wars. Friends, in 2012, addressed girls with a new figure taller and more detailed than the minifigure, a small town called Heartlake City, and colours that the classic range had ignored. It was criticised in advance and became one of the largest lines in the company's history.

Then came the film. The LEGO Movie was released in February 2014, directed by Phil Lord and Christopher Miller, and it did something nobody expected of a feature-length advertisement: it was good. The story of an ordinary construction worker minifigure who is mistaken for a hero, and the ending that revealed the whole plot as a game played by a boy and his father, was funny and sincere at once. It earned nearly half a billion dollars in cinemas and gave the company a song about how everything is awesome that parents could not remove from their heads for years. Sequels and spin-offs followed with less impact, but the first film changed how the brand was seen.

By 2015 the LEGO Group had become, by revenue, the largest toy company in the world, passing Mattel. Factories ran around the clock and still could not meet demand in the Christmas season. The company that had almost died in 2003 was earning more profit than any of its competitors, without a single share on any stock exchange, still owned by the family through a holding company in Billund.

In 2017 Jørgen Vig Knudstorp moved to chair the board, and Niels B. Christiansen, an engineer from the Danish industrial group Danfoss, became chief executive. The same year the LEGO House opened in Billund, a building of white stacked blocks designed by the architect Bjarke Ingels, part museum, part playground, with a tree of creativity fifteen metres tall built from more than six million bricks.""",

"""THE HISTORY OF LEGO — PART NINE: THE BRICK AND ITS FUTURE

A brick made of ABS plastic will last for centuries if it is not stepped on, and a company that has sold hundreds of billions of them has to think about what happens to them. From the 2010s the LEGO Group made sustainability a public commitment, and it turned out to be harder than a press release.

In 2018 the first elements made from plant-based polyethylene appeared: trees, leaves and bushes, soft pieces that could be made from sugarcane without changing how they felt. The hard bricks were another matter. ABS is a good material precisely because it is stiff, holds a precise shape and keeps its colour, and the substitutes tested over the years bent, faded or did not click properly. In 2021 the company announced a prototype brick made from recycled drinks bottles, and in 2023 it announced that the prototype had been abandoned, because making it at scale would have produced more carbon than the plastic it replaced. The search continued with other materials, and the company began to talk of a mixture of approaches rather than one miracle brick.

Other programmes were less dramatic and more effective. LEGO Replay, started in the United States in 2019, collects used bricks, cleans them and gives them to children's charities. Packaging moved from plastic bags inside boxes to paper ones. The factories in Denmark, Hungary, Mexico, the Czech Republic, China and, from the mid-2020s, Vietnam and the United States, were built or rebuilt with the aim of running on renewable electricity.

The brick also found uses far from the toy shelf. LEGO Braille Bricks, developed with associations for the blind and launched for schools in 2020, use the studs to teach the Braille alphabet; a version for families followed. LEGO Serious Play, a method developed in the 1990s, uses bricks in corporate workshops to make adults build models of problems instead of talking about them. Hospitals use Duplo to explain procedures to children. Researchers use bricks to build cheap laboratory equipment because the tolerances are better than most things they can afford.

Adult fans, once an anomaly, became a market. The company created a range for them under the name LEGO Icons, and adult sets now include flowers that never wilt, a world map, a large Titanic more than a metre long, and cars from Ferrari, Lamborghini and McLaren. Conventions of adult builders are held on every continent, and the phrase "adult fan of LEGO" has its own abbreviation. The yellow neutral face was joined over the decades by thousands of printed faces, flesh tones for figures based on real actors, and figures in wheelchairs and with hearing aids.

Video games and films kept the brand in front of children who might never open a box. The LEGO Star Wars games, made by the British studio Traveller's Tales from 2005, sold tens of millions of copies with a simple formula of destroying everything in sight and rebuilding it. Ninjago and Friends ran for years on television. In 2022 the company acquired a stake in Epic Games to build a LEGO world inside Fortnite, an admission that the afternoon hours once lost to arcades now had to be won back inside other people's games.

None of this changed the object itself. The two-by-four brick made today has the same studs, the same tubes and the same dimensions as the one patented in 1958, and it will still hold a brick from 1958 with the same grip. Fashion in toys changes every year. The company's whole history is the argument that a good enough object does not have to.""",

"""THE HISTORY OF LEGO — PART TEN: WHAT THE STORY IS ABOUT

Nearly a century after a carpenter in Billund began making wooden ducks, the LEGO Group employs more than twenty thousand people, sells in more than one hundred and thirty countries, and makes somewhere in the region of one hundred billion elements a year. Its bricks have been to the International Space Station, to the top of mountains and to the bottom of the sea. There are, on average, more LEGO minifigures on the planet than there are people in some countries, and the minifigure is one of the most produced human figures in history.

It is tempting to tell the story as a series of inventions: the plastic machine in 1946, the System in 1955, the tube in 1958, the minifigure in 1978, the programmable brick in 1998. Each of those changed the product. But the pattern underneath them is a sequence of decisions to stop doing something. Ole Kirk stopped building houses when nobody could pay for them. Godtfred stopped making wooden toys after a fire and stopped licensing to Samsonite when the quality slipped. Jørgen Vig Knudstorp stopped running theme parks, stopped making fourteen thousand different elements, and stopped pretending that a lifestyle brand was more interesting than a plastic brick. Each time, the company got smaller for a while and then grew larger than before.

The other pattern is the refusal to be sold. The family has turned down offers for decades, has never listed the company, and has kept it in a town of a few thousand people in the middle of Jutland where the head office, the largest factory, the airport, the theme park and the LEGO House all stand within walking distance of the original workshop. The town exists in its present form because of the company, and the company has stayed in the town because leaving would have meant becoming something else.

There is also the matter of the customers. A child who receives a box of bricks receives nothing finished. The box contains parts and a suggestion, and the child has to do the rest, and the child can ignore the suggestion entirely. Every other successful toy of the last hundred years has told the child what it is. The brick asks the child what it will be. That is why the company's own designers spend so much time watching children play, why adult fans were eventually let inside, and why a set designed by a fan in Chile or Japan can end up on shelves everywhere. The product is open at the end, and the company learned, slowly and sometimes painfully, to be open at the end as well.

The motto carved in the workshop in the 1930s still hangs there, and it is worth reading it the way the carpenter meant it. Only the best is good enough was not about ambition. It was about a batch of wooden ducks that had received two coats of varnish instead of three, and a father who sent his son back to finish the job. The whole of the history is in that evening: the insistence that a small thing for a child deserves to be made properly, even when nobody will notice, and even when it costs more than it should.

END OF THE HISTORY OF LEGO."""
]

TOTAL = sum(len(p) for p in PARTS)
