#!/usr/bin/env python3
"""
Local design-preview builder (NOT for production).

The preview dev server is `python3 -m http.server 8080`, and the screenshot
tool always captures the server root `/`. A bare `/` shows the directory
listing, so this script writes a throwaway copy of the app to `index.html`
(served at `/`) with a tiny hook that auto-opens the crypto wallet-picker
sheet on load. That lets us screenshot the real, fully-styled component.

  - Source of truth stays `index-6.html` (never modified).
  - Output `index.html` is git-ignored and safe to delete anytime.
  - Animations/transitions are disabled in the copy so the headless
    compositor gets a stable frame (otherwise the slide-in transition
    stays "running" and screenshots fail / capture mid-animation).

Usage:
    python3 tools/preview_build.py                # default 565 AED invoice
    python3 tools/preview_build.py --amount 1200  # custom amount
    python3 tools/preview_build.py --clean        # remove index.html

Then point the preview at http://localhost:8080/ and screenshot.
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "index-6.html")
OUT = os.path.join(HERE, "index.html")

HOOK = """<script>/*__CPW_PREVIEW_ONLY__ generated by tools/preview_build.py*/
(function p(){{try{{
  if(typeof cryptoCreateInvoice==='function'&&typeof openCryptoWalletSheet==='function'&&document.getElementById('cpw-ov')){{
    var s=document.createElement('style');
    s.textContent='*,*::before,*::after{{transition:none !important;animation:none !important}}';
    document.head.appendChild(s);
    cryptoInvoice=cryptoCreateInvoice('AMBPREVIEW',{amount});
    try{{renderInvoice();}}catch(e){{}}
    openCryptoWalletSheet();
    document.documentElement.setAttribute('data-cpwprev','on');
    return;
  }}
}}catch(e){{document.documentElement.setAttribute('data-cpwprev','err:'+e);}}
setTimeout(p,120);}})();
</script>
"""


def build(amount):
    if not os.path.exists(SRC):
        sys.exit(f"source not found: {SRC}")
    src = open(SRC, "r", encoding="utf-8").read()
    idx = src.rfind("</body>")
    if idx == -1:
        sys.exit("no </body> found in source")
    out = src[:idx] + HOOK.format(amount=amount) + src[idx:]
    open(OUT, "w", encoding="utf-8").write(out)
    print(f"wrote {OUT} ({len(out)} bytes) — open http://localhost:8080/ and screenshot")


def clean():
    if os.path.exists(OUT):
        os.remove(OUT)
        print(f"removed {OUT}")
    else:
        print("nothing to clean")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Build/remove the local design-preview copy.")
    ap.add_argument("--amount", type=int, default=565, help="invoice amount in AED (default 565)")
    ap.add_argument("--clean", action="store_true", help="remove the generated index.html")
    args = ap.parse_args()
    clean() if args.clean else build(args.amount)
